package com.example.CRUD.controllers;

import com.example.CRUD.models.ResponseModel;
import com.example.CRUD.models.UserModel;
import com.example.CRUD.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController // This means that this class is a Controller
@RequestMapping("/users") // This means URL's start with /users (after Application path)
public class UserController {

    @Autowired// This means to get the bean called service
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserService service;

    @GetMapping(path = "/{id}") // Map ONLY GET Requests
    ResponseModel<UserModel> get(@PathVariable Integer id) {
        return service.get(id);
    }

    @DeleteMapping(path = "/{id}") // Map ONLY DELETE Requests
    ResponseModel<UserModel> delete(@PathVariable Integer id) {
        return service.deleteById(id);
    }

    @PostMapping // Map ONLY POST Requests
    ResponseModel<UserModel> insert(@RequestBody UserModel model) {
        return service.insert(model);
    }

    @PutMapping // Map ONLY PUT Requests
    ResponseModel<UserModel> update(@RequestBody UserModel model) {
        return service.update(model);
    }

}
